services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    cm.create_congregation:
        class: CongregationManager\Application\Congregation\CreateCongregation
        arguments:
            - '@cm.repository.congregation'

    cm.create_brother:
        class: CongregationManager\Application\Congregation\CreateBrother
        arguments:
            - '@cm.repository.brother'
