services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    cm.create_congregation:
        class: CongregationManager\Application\Congregation\CreateCongregation
        arguments:
            - '@cm.repository.congregation'

    cm.create_brother:
        class: CongregationManager\Application\Congregation\CreateBrother
        arguments:
            - '@cm.repository.brother'

    cm.create_app_user:
        class: CongregationManager\Application\User\CreateAppUser
        arguments:
            - '@cm.repository.app_user'
            - '@cm.hasher.user_password'

    cm.create_admin_user:
        class: CongregationManager\Infrastructure\User\Action\CreateAdminUser
        arguments:
            - '@cm.repository.admin_user'
            - '@cm.hasher.user_password'

    cm.create_app_user_invitation:
        class: CongregationManager\Infrastructure\User\Action\CreateAppUserInvitation
        arguments:
            - '@cm.generator.token'
            - '@cm.repository.app_user_invitation'
