services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    cm.command.create_congregation:
        class: CongregationManager\Bundle\Congregation\Command\CreateCongregationCommand
        arguments:
            - '@cm.utils.validator'
            - '@cm.create_congregation'
            - '@doctrine.orm.entity_manager'
            - 'app:create-congregation'
        tags:
            - { name: 'console.command' }

    cm.command.create_admin_user:
        class: CongregationManager\Bundle\User\Command\CreateAdminUserCommand
        arguments:
            - '@cm.create_admin_user'
            - '@doctrine.orm.entity_manager'
            - '@cm.utils.validator'
            - '%default_locale%'
            - '%supported_locales%'
            - 'app:create-admin-user'
        tags:
            - { name: 'console.command' }

    cm.command.import_from_old_cm:
        class: CongregationManager\Bundle\Core\Command\ImportFromOldCMCommand
        arguments:
            - '@cm.repository.old_cm.congregation'
            - '@cm.create_congregation'
            - '@doctrine.orm.entity_manager'
            - '@cm.repository.old_cm.brother'
            - '@cm.create_brother'
            - '@cm.repository.old_cm.app_user'
            - '@cm.create_app_user'
            - '@cm.repository.old_cm.province'
            - '@cm.create_province'
            - '@cm.repository.old_cm.municipality'
            - '@cm.create_municipality'
            - '@cm.repository.old_cm.area'
            - '@cm.create_area'
            - '@cm.repository.old_cm.territory'
            - '@cm.create_territory'
            - '@cm.repository.old_cm.territory_assignment'
            - '@cm.create_territory_assignment'
            - 'app:import-from-old-cm'
        tags:
            - { name: 'console.command' }
