services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    cm.context.locale:
        class: CongregationManager\Bundle\Core\Context\LocaleContext
        arguments:
            - '@request_stack'

    cm.context.congregation:
        class: CongregationManager\Bundle\Core\Context\CongregationContext
        arguments:
            - '@security.helper'
