services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    app.controller.homepage:
        class: App\Infrastructure\Common\Controller\HomePageController
        arguments:
            - '%supported_locales%'
        calls:
            - [setContainer, ['@service_container']]
        tags: [ 'controller.service_arguments' ]

    app.controller.app_locale:
        class: App\Infrastructure\Common\Controller\AppLocaleController
        arguments:
            - '%supported_locales%'
            - '@session'
        calls:
            - [setContainer, ['@service_container']]
        tags: [ 'controller.service_arguments' ]

    app.controller.app_user_login:
        class: App\Infrastructure\User\Controller\AppUserLoginController
        arguments:
            - '@security.authentication_utils'
        calls:
            - [setContainer, ['@service_container']]
        tags: [ 'controller.service_arguments' ]

    app.controller.app_dashboard:
        class: App\Infrastructure\Common\Controller\AppDashboardController
        calls:
            - [setContainer, ['@service_container']]
        tags: [ 'controller.service_arguments' ]

    app.controller.admin_locale:
        class: App\Infrastructure\Common\Controller\AdminLocaleController
        arguments:
            - '%supported_locales%'
            - '@session'
        calls:
            - [setContainer, ['@service_container']]
        tags: [ 'controller.service_arguments' ]

    app.controller.admin_user_login:
        class: App\Infrastructure\User\Controller\AdminUserLoginController
        arguments:
            - '@security.authentication_utils'
        calls:
            - [setContainer, ['@service_container']]
        tags: [ 'controller.service_arguments' ]

    app.controller.admin_dashboard:
        class: App\Infrastructure\Common\Controller\AdminDashboardController
        calls:
            - [setContainer, ['@service_container']]
        tags: [ 'controller.service_arguments' ]

    app.controller.reset_app_password:
        class: App\Infrastructure\User\Controller\ResetAppPasswordController
        arguments:
            - '@symfonycasts.reset_password.helper'
            - '@doctrine.orm.entity_manager'
            - '@mailer.mailer'
            - '@security.user_password_hasher'
            - '@logger'
        calls:
            - [setContainer, ['@service_container']]
        tags: [ 'controller.service_arguments' ]

    app.controller.app_change_password:
        class: App\Infrastructure\User\Controller\AppChangePasswordController
        arguments:
            - '@security.helper'
            - '@doctrine.orm.entity_manager'
            - '@translator'
            - '@security.user_password_hasher'
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags: [ 'controller.service_arguments' ]

    app.controller.reset_admin_password:
        class: App\Infrastructure\User\Controller\ResetAdminPasswordController
        arguments:
            - '@symfonycasts.reset_password.helper'
            - '@doctrine.orm.entity_manager'
            - '@mailer.mailer'
            - '@security.user_password_hasher'
            - '@logger'
        calls:
            - [setContainer, ['@service_container']]
        tags: [ 'controller.service_arguments' ]

    app.controller.app_profile:
        class: App\Infrastructure\User\Controller\AppProfileController
        arguments:
            - '@security.helper'
            - '@doctrine.orm.entity_manager'
            - '@translator'
        calls:
            - [setContainer, ['@service_container']]
        tags: [ 'controller.service_arguments' ]

    app.controller.admin_profile:
        class: App\Infrastructure\User\Controller\AdminProfileController
        arguments:
            - '@security.helper'
            - '@doctrine.orm.entity_manager'
            - '@translator'
        calls:
            - [setContainer, ['@service_container']]
        tags: [ 'controller.service_arguments' ]

    app.controller.admin_change_password:
        class: App\Infrastructure\User\Controller\AdminChangePasswordController
        arguments:
            - '@security.helper'
            - '@doctrine.orm.entity_manager'
            - '@translator'
            - '@security.user_password_hasher'
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags: [ 'controller.service_arguments' ]
