services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    cm.converter.locale:
        class: CongregationManager\Bundle\Core\Converter\LocaleConverter
        arguments:
            - '%default_locale%'
