services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    cm.event_subscriber.locale:
        class: CongregationManager\Bundle\Core\EventSubscriber\LocaleSubscriber
        arguments:
            - '%default_locale%'
            - '%supported_locales%'
        tags:
            - { name: kernel.event_subscriber }

    cm.event_subscriber.user_locale:
        class: CongregationManager\Bundle\Core\EventSubscriber\UserLocaleSubscriber
        arguments:
            - '@request_stack'
            - '%supported_locales%'
        tags:
            - { name: kernel.event_subscriber }
