services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    cm.form.type.reset_password_request:
        class: CongregationManager\Infrastructure\User\Form\ResetPasswordRequestFormType
        tags:
            - { name: 'form.type' }

    cm.form.type.change_password:
        class: CongregationManager\Infrastructure\User\Form\ChangePasswordFormType
        tags:
            - { name: 'form.type' }

    cm.form.type.brother:
        class: CongregationManager\Infrastructure\Congregation\Form\UpdateBrotherFormType
        tags:
            - { name: 'form.type' }

    cm.form.type.email:
        class: CongregationManager\Infrastructure\User\Form\ChangeEmailFormType
        tags:
            - { name: 'form.type' }

    cm.form.type.profile_update:
        class: CongregationManager\Infrastructure\Common\Form\ProfileUpdateFormType
        tags:
            - { name: 'form.type' }

    cm.form.type.user_invite:
        class: CongregationManager\Infrastructure\User\Form\InviteUserFormType
        tags:
            - { name: 'form.type' }

    cm.form.type.complete_account:
        class: CongregationManager\Infrastructure\User\Form\CompleteAccountFormType
        tags:
            - { name: 'form.type' }

    cm.form.type.territory_filters:
        class: CongregationManager\Infrastructure\Territory\Form\TerritoryFiltersFormType
        tags:
            - { name: 'form.type' }
