services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    cm.command.handler.create_territory_assignment:
        class: CongregationManager\Component\TerritoryManager\Application\Command\CreateTerritoryAssignmentHandler
        arguments:
            - '@cm.factory.territory_assignment'
            - '@cm.repository.territory_assignment'

    cm.command.handler.update_territory_assignment:
        class: CongregationManager\Component\TerritoryManager\Application\Command\UpdateTerritoryAssignmentHandler
        arguments:
            - '@cm.repository.territory_assignment'
