services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    cm.repository.app_user:
        alias: 'CongregationManager\Bundle\User\Repository\AppUserRepository'

    CongregationManager\Bundle\User\Repository\AppUserRepository:
        arguments:
            - '@doctrine'
        tags:
            - { name: doctrine.repository_service }

    cm.repository.admin_user:
        alias: 'CongregationManager\Bundle\User\Repository\AdminUserRepository'

    CongregationManager\Bundle\User\Repository\AdminUserRepository:
        arguments:
            - '@doctrine'
        tags:
            - { name: doctrine.repository_service }

    cm.repository.reset_password_request:
        alias: 'CongregationManager\Bundle\User\Repository\ResetPasswordRequestRepository'

    CongregationManager\Bundle\User\Repository\ResetPasswordRequestRepository:
        arguments:
            - '@doctrine'
        tags:
            - { name: doctrine.repository_service }

    cm.repository.congregation:
        alias: 'CongregationManager\Bundle\Congregation\Repository\CongregationRepository'

    CongregationManager\Bundle\Congregation\Repository\CongregationRepository:
        arguments:
            - '@doctrine'
        tags:
            - { name: doctrine.repository_service }

    cm.repository.brother:
        alias: 'CongregationManager\Bundle\Congregation\Repository\BrotherRepository'

    CongregationManager\Bundle\Congregation\Repository\BrotherRepository:
        arguments:
            - '@doctrine'
        tags:
            - { name: doctrine.repository_service }

    cm.repository.app_user_invitation:
        alias: 'CongregationManager\Bundle\User\Repository\AppUserInvitationRepository'

    CongregationManager\Bundle\User\Repository\AppUserInvitationRepository:
        arguments:
            - '@doctrine'
        tags:
            - { name: doctrine.repository_service }

    cm.repository.province:
        alias: 'CongregationManager\Bundle\TerritoryManager\Repository\ProvinceRepository'

    CongregationManager\Bundle\TerritoryManager\Repository\ProvinceRepository:
        arguments:
            - '@doctrine'
        tags:
            - { name: doctrine.repository_service }

    cm.repository.municipality:
        alias: 'CongregationManager\Bundle\TerritoryManager\Repository\MunicipalityRepository'

    CongregationManager\Bundle\TerritoryManager\Repository\MunicipalityRepository:
        arguments:
            - '@doctrine'
        tags:
            - { name: doctrine.repository_service }

    cm.repository.area:
        alias: 'CongregationManager\Bundle\TerritoryManager\Repository\AreaRepository'

    CongregationManager\Bundle\TerritoryManager\Repository\AreaRepository:
        arguments:
            - '@doctrine'
        tags:
            - { name: doctrine.repository_service }

    cm.repository.territory:
        alias: 'CongregationManager\Bundle\TerritoryManager\Repository\TerritoryRepository'

    CongregationManager\Bundle\TerritoryManager\Repository\TerritoryRepository:
        arguments:
            - '@doctrine'
        tags:
            - { name: doctrine.repository_service }

    cm.repository.territory_assignment:
        alias: 'CongregationManager\Bundle\TerritoryManager\Repository\TerritoryAssignmentRepository'

    CongregationManager\Bundle\TerritoryManager\Repository\TerritoryAssignmentRepository:
        arguments:
            - '@doctrine'
        tags:
            - { name: doctrine.repository_service }

    cm.repository.old_cm.congregation:
        class: CongregationManager\Bundle\Core\Repository\OldCM\CongregationRepository
        arguments:
            - '@doctrine.dbal.old_cm_connection'

    cm.repository.old_cm.brother:
        class: CongregationManager\Bundle\Core\Repository\OldCM\BrotherRepository
        arguments:
            - '@doctrine.dbal.old_cm_connection'

    cm.repository.old_cm.app_user:
        class: CongregationManager\Bundle\Core\Repository\OldCM\AppUserRepository
        arguments:
            - '@doctrine.dbal.old_cm_connection'

    cm.repository.old_cm.province:
        class: CongregationManager\Bundle\Core\Repository\OldCM\ProvinceRepository
        arguments:
            - '@doctrine.dbal.old_cm_connection'

    cm.repository.old_cm.municipality:
        class: CongregationManager\Bundle\Core\Repository\OldCM\MunicipalityRepository
        arguments:
            - '@doctrine.dbal.old_cm_connection'

    cm.repository.old_cm.area:
        class: CongregationManager\Bundle\Core\Repository\OldCM\AreaRepository
        arguments:
            - '@doctrine.dbal.old_cm_connection'

    cm.repository.old_cm.territory:
        class: CongregationManager\Bundle\Core\Repository\OldCM\TerritoryRepository
        arguments:
            - '@doctrine.dbal.old_cm_connection'

    cm.repository.old_cm.territory_assignment:
        class: CongregationManager\Bundle\Core\Repository\OldCM\TerritoryAssignmentRepository
        arguments:
            - '@doctrine.dbal.old_cm_connection'
