services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    app.repository.app_user:
        alias: 'App\Infrastructure\User\Repository\AppUserRepository'

    App\Infrastructure\User\Repository\AppUserRepository:
        arguments:
            - '@doctrine'
        tags:
            - { name: doctrine.repository_service }

    app.repository.admin_user:
        alias: 'App\Infrastructure\User\Repository\AdminUserRepository'

    App\Infrastructure\User\Repository\AdminUserRepository:
        arguments:
            - '@doctrine'
        tags:
            - { name: doctrine.repository_service }

    app.repository.reset_app_password_request:
        alias: 'App\Infrastructure\User\Repository\ResetAppPasswordRequestRepository'

    App\Infrastructure\User\Repository\ResetAppPasswordRequestRepository:
        arguments:
            - '@doctrine'
        tags:
            - { name: doctrine.repository_service }
