services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    cm.twig.extension.test_html_attribute:
        class: CongregationManager\Bundle\Core\Twig\TestHtmlAttributeExtension
        arguments:
            - '%kernel.environment%'
        tags:
            - { name: twig.extension }

    cm.twig.extension.test_form_attribute:
        class: CongregationManager\Bundle\Core\Twig\TestFormAttributeExtension
        arguments:
            - '%kernel.environment%'
        tags:
            - { name: twig.extension }

    cm.twig.extension.locale:
        class: CongregationManager\Bundle\Core\Twig\LocaleExtension
        tags:
            - { name: twig.extension }

    cm.twig.runtime.locale:
        class: CongregationManager\Bundle\Core\Twig\LocaleRuntime
        arguments:
            - '@cm.converter.locale'
            - '@cm.context.locale'
        tags:
            - { name: twig.runtime }
