services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    app.twig.extension.test_html_attribute:
        class: App\Infrastructure\Common\Twig\TestHtmlAttributeExtension
        arguments:
            - '%kernel.environment%'
        tags:
            - { name: twig.extension }

    app.twig.extension.locale:
        class: App\Infrastructure\Common\Twig\LocaleExtension
        tags:
            - { name: twig.extension }

    app.twig.runtime.locale:
        class: App\Infrastructure\Common\Twig\LocaleRuntime
        arguments:
            - '@app.converter.locale'
        tags:
            - { name: twig.runtime }
