services:
    ###> doctrine/doctrine-bundle ###
    database:
        environment:
            POSTGRES_DB: congregation-manager
            POSTGRES_PASSWORD: ChangeMe
            POSTGRES_USER: webapp
        ports:
            - "5432:5432"
    ###< doctrine/doctrine-bundle ###
    mail:
        ports:
            - "8025:8025"
            - "1025:1025"
