<?php

use PhpCsFixer\Fixer\ArrayNotation\ArraySyntaxFixer;
use PhpCsFixer\Fixer\Strict\StrictComparisonFixer;
use Symplify\EasyCodingStandard\Config\ECSConfig;
use Symplify\EasyCodingStandard\ValueObject\Set\SetList;

return static function (ECSConfig $ecsConfig): void {
    $ecsConfig->rule(ArraySyntaxFixer::class);
    $ecsConfig->sets([
        SetList::PSR_12,
        SetList::CLEAN_CODE,
        SetList::SYMPLIFY,
        SetList::ARRAY,
        SetList::COMMENTS,
        SetList::DOCBLOCK,
        SetList::NAMESPACES,
        SetList::PHPUNIT,
        #SetList::SPACES,
        SetList::STRICT,
        SetList::CONTROL_STRUCTURES,
        SetList::CLEAN_CODE,
    ]);
    $ecsConfig->skip([
        StrictComparisonFixer::class => [
            'src/Domain/Territory/Model/TerritoryAssignment.php',
        ],
        'tests/bootstrap.php',
        // generated by Doctrine
        __DIR__ . '/src/CongregationManager/Bundle/Core/Migrations',
    ]);
};
