<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;

return RectorConfig::configure()
    ->withPaths([
        __DIR__ . '/config',
        __DIR__ . '/public',
        __DIR__ . '/src',
        __DIR__ . '/tests',
    ])
    ->withSkip([
        __DIR__ . '/public/index.php',
        // generated by Doctrine
        __DIR__ . '/src/CongregationManager/Bundle/*/Migrations/*',
    ])
    ->withPhpSets(true)
    ->withTypeCoverageLevel(0)
;
