<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    Symfony\WebpackEncoreBundle\WebpackEncoreBundle::class => ['all' => true],
    FriendsOfBehat\SymfonyExtension\Bundle\FriendsOfBehatSymfonyExtensionBundle::class => ['test' => true],
    Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['dev' => true, 'test' => true],
    DAMA\DoctrineTestBundle\DAMADoctrineTestBundle::class => ['test' => true],
    SymfonyCasts\Bundle\ResetPassword\SymfonyCastsResetPasswordBundle::class => ['all' => true],
    Knp\Bundle\PaginatorBundle\KnpPaginatorBundle::class => ['all' => true],
    CongregationManager\Bundle\Resource\CongregationManagerResourceBundle::class => ['all' => true],
    CongregationManager\Bundle\Congregation\CongregationManagerCongregationBundle::class  => ['all' => true],
    CongregationManager\Bundle\TerritoryManager\CongregationManagerTerritoryManagerBundle::class => ['all' => true],
    CongregationManager\Bundle\CQRS\CongregationManagerCQRSBundle::class => ['all' => true],
    CongregationManager\Bundle\User\CongregationManagerUserBundle::class => ['all' => true],
    CongregationManager\Bundle\Core\CongregationManagerCoreBundle::class => ['all' => true],
    CongregationManager\Bundle\App\CongregationManagerAppBundle::class  => ['all' => true],
    CongregationManager\Bundle\Admin\CongregationManagerAdminBundle::class  => ['all' => true],
];
