parameters:
    app_admin.path_name: 'admin'
    default_locale: 'en'
    supported_locales: en|it

imports:
    - { resource: "services/*.yaml" }

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

