app_territory_index:
    path: /territories
    methods: [GET]
    defaults:
        _controller: cm.controller.app_territory::index

app_territory_show:
    path: /territory/{id}
    methods: [GET]
    defaults:
        _controller: cm.controller.app_territory::show

app_territory_assign:
    path: /territory/{territoryId}/assign
    methods: [GET, POST]
    defaults:
        _controller: cm.controller.app_territory_assignment::create
