---
-
    hosts: webserver

    vars_files:
        - ./vars/vault.yml
        - ./vars/vars.yml

    vars_prompt:
        -
            name: project_env
            prompt: "Enter the environment for your project app (prod|dev|test)"
            default: prod
            private: no

    environment:
        APP_ENV: "{{ project_env|lower }}"

    pre_tasks:
        -
            name: Convert entered project environment to lowercase
            set_fact:
                project_env: "{{ project_env|lower }}"
            tags:
                - always
        -
            name: Update APT package manager repositories cache
            become: true
            apt:
                update_cache: yes
            changed_when: false

        -
            name: Upgrade installed packages
            become: true
            apt:
                upgrade: safe # This option requires "aptitude", be sure that is installed on your distro or add it via apt before these command

    roles:
        - apache

    tasks:
        -
            ping: ~

        -
            name: Install cowsay - it's probably important
            become: true
            apt:
                name: cowsay

        -
            name: Install low-level utilities
            become: true
            apt:
                name:
                    - zip
                    - unzip
                state: latest

        -
            name: Install Git VCS
            become: true
            apt:
                name: git
                state: latest

        -
            name: Install PostgreSQL DB server
            become: true
            apt:
                name:
                    - postgresql
                    - postgresql-contrib
                state: latest

        -
            name: Add PHP PPA repository
            become: true
            apt_repository:
                repo: ppa:ondrej/php

        -
            name: Install PHP packages
            become: true
            apt:
                name:
                    - php8.0
                    - php8.0-fpm
                    - php8.0-xml
                    - php8.0-pgsql
                    - php8.0-sqlite3 #TODO: Remove this
                    - php8.0-mbstring #TODO: Remove this
                state: latest
            notify: Restart PHP-FPM

        -
            name: Set date.timezone for CLI
            become: true
            lineinfile:
                path: /etc/php/8.0/cli/php.ini
                regexp: "date.timezone ="
                line: "date.timezone = Europe/Rome"
            notify: Restart PHP-FPM

        -
            name: Set date.timezone for FPM
            become: true
            lineinfile:
                path: /etc/php/8.0/fpm/php.ini
                regexp: "date.timezone ="
                line: "date.timezone = Europe/Rome"

        -
            name: Check for Composer
            stat:
                path: /usr/local/bin/composer
            register: composer_stat
            tags:
                - deploy

        -
            name: Download Composer
            script: scripts/install_composer.sh
            when: not composer_stat.stat.exists
            tags:
                - deploy

        -
            name: Move Composer globally
            become: true
            command: mv composer.phar /usr/local/bin/composer
            when: not composer_stat.stat.exists
            tags:
                - deploy

        -
            name: Set permissions on Composer
            become: true
            file:
                path: /usr/local/bin/composer
                mode: "a+x"
            when: not composer_stat.stat.exists
            tags:
                - deploy

        -
            name: Make sure composer is at its latest version
            composer:
                working_dir: "{{ project_root_dir }}"
                command: self-update
            when: composer_stat.stat.exists
            register: composer_self_update
            changed_when: "not composer_self_update.stdout|regex_search('You are already using the latest available Composer')"
            tags:
                - deploy

        -
            name: Create project directory and set its permissions
            become: true
            file:
                path: "{{ project_root_dir }}"
                state: directory
                owner: "{{ ansible_user }}"
                group: "{{ ansible_user }}"
                recurse: yes
            tags:
                - deploy

        -
            name: Checkout Git repository
            git:
                repo: https://github.com/symfony/demo
                dest: "{{ project_root_dir }}"
                force: yes
            changed_when: false
            register: repo_code
            tags:
                - deploy

        -
            name: Register code_changed variable
            set_fact:
                code_changed: repo_code.changed
            tags:
                - deploy

        # Bootstrap project app
        -
            import_tasks: ./includes/project-bootstrap.yml

    handlers:
        -
            name: Restart PHP-FPM
            become: true
            service:
                name: php8.0-fpm
                state: restarted
