admin_forgot_password_request:
    path: /
    methods: [GET, POST]
    defaults:
        _controller: cm.controller.reset_admin_password:request

admin_check_email:
    path: /check-email
    methods: [GET]
    defaults:
        _controller: cm.controller.reset_admin_password:checkEmail

admin_reset_password:
    path: /reset/{token}
    methods: [GET, POST]
    defaults:
        _controller: cm.controller.reset_admin_password:reset
        token: null
