admin_index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'admin_login'
        permanent: true
        keepQueryParams: true
        keepRequestMethod: false

admin_switch_locale:
    path: /switch-locale/{locale}
    methods: [GET]
    defaults:
        locale: '%supported_locales%'
        _controller: cm.controller.admin_locale::switchLocale

admin_login:
    path: /login
    methods: [GET]
    defaults:
        _controller: cm.controller.admin_user_login::index

admin_login_check:
    path: /login-check
    methods: [POST]

admin_logout:
    path: /logout
    methods: GET

admin_dashboard:
    path: /dashboard
    methods: [GET]
    defaults:
        _controller: cm.controller.admin_dashboard::index

admin_profile_update:
    path: /profile/update
    methods: [GET, POST]
    defaults:
        _controller: cm.controller.admin_profile::update

admin_change_password:
    path: /password/update
    methods: [GET, POST]
    defaults:
        _controller: cm.controller.admin_change_password::update

admin_congregation_index:
    path: /congregations
    methods: [GET]
    defaults:
        _controller: cm.controller.admin_congregation::index

admin_congregation_show:
    path: /congregation/{id}
    methods: [GET]
    defaults:
        _controller: cm.controller.admin_congregation::show

admin_brother_index:
    path: /brothers
    methods: [GET]
    defaults:
        _controller: cm.controller.admin_brother::index

admin_brother_show:
    path: /brother/{id}
    methods: [GET]
    defaults:
        _controller: cm.controller.admin_brother::show
