app_homepage:
    path: /
    methods: [GET]
    defaults:
        _controller: app.controller.homepage:index

app_login:
    path: /login
    methods: [GET]
    defaults:
        _controller: app.controller.app_user_login:index

app_login_check:
    path: /login-check
    methods: [POST]

app_logout:
    path: /logout
    methods: GET

app_dashboard:
    path: /dashboard
    methods: [GET]
    defaults:
        _controller: app.controller.app_dashboard:index
